#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Access
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FreightSystemDB")]
	public partial class SQLDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTransportRecords(TransportRecords instance);
    partial void UpdateTransportRecords(TransportRecords instance);
    partial void DeleteTransportRecords(TransportRecords instance);
    partial void InsertTransportRecordsOptionHistory(TransportRecordsOptionHistory instance);
    partial void UpdateTransportRecordsOptionHistory(TransportRecordsOptionHistory instance);
    partial void DeleteTransportRecordsOptionHistory(TransportRecordsOptionHistory instance);
    partial void InsertMenuAccess(MenuAccess instance);
    partial void UpdateMenuAccess(MenuAccess instance);
    partial void DeleteMenuAccess(MenuAccess instance);
    partial void InsertMenuItem(MenuItem instance);
    partial void UpdateMenuItem(MenuItem instance);
    partial void DeleteMenuItem(MenuItem instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertBusinessArea(BusinessArea instance);
    partial void UpdateBusinessArea(BusinessArea instance);
    partial void DeleteBusinessArea(BusinessArea instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    #endregion
		
		public SQLDBDataContext() : 
				base(global::DAO_Access.Properties.Settings.Default.FreightSystemDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TransportRecords> TransportRecords
		{
			get
			{
				return this.GetTable<TransportRecords>();
			}
		}
		
		public System.Data.Linq.Table<TransportRecordsOptionHistory> TransportRecordsOptionHistory
		{
			get
			{
				return this.GetTable<TransportRecordsOptionHistory>();
			}
		}
		
		public System.Data.Linq.Table<MenuAccess> MenuAccess
		{
			get
			{
				return this.GetTable<MenuAccess>();
			}
		}
		
		public System.Data.Linq.Table<MenuItem> MenuItem
		{
			get
			{
				return this.GetTable<MenuItem>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<BusinessArea> BusinessArea
		{
			get
			{
				return this.GetTable<BusinessArea>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransportRecords")]
	public partial class TransportRecords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarLicense;
		
		private string _ClientName;
		
		private System.DateTime _DeliverDate;
		
		private string _Driver;
		
		private string _FromLocation;
		
		private string _PackageName;
		
		private int _Quantity;
		
		private string _ToLocation;
		
		private double _Volume;
		
		private System.Nullable<double> _AccountPayble;
		
		private string _Comment;
		
		private System.Nullable<double> _Deductions;
		
		private System.Nullable<double> _DeliverPrice;
		
		private string _DeliverType;
		
		private System.Nullable<double> _HandlingFee;
		
		private System.Nullable<System.DateTime> _PayDate;
		
		private System.Nullable<double> _PrePay;
		
		private System.Nullable<double> _OilCard;
		
		private System.Nullable<double> _Reparations;
		
		private System.Nullable<double> _ShortBargeFee;
		
		private string _Status;
		
		private string _TrayNo;
		
		private EntitySet<TransportRecordsOptionHistory> _TransportRecordsOptionHistory;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarLicenseChanging(string value);
    partial void OnCarLicenseChanged();
    partial void OnClientNameChanging(string value);
    partial void OnClientNameChanged();
    partial void OnDeliverDateChanging(System.DateTime value);
    partial void OnDeliverDateChanged();
    partial void OnDriverChanging(string value);
    partial void OnDriverChanged();
    partial void OnFromLocationChanging(string value);
    partial void OnFromLocationChanged();
    partial void OnPackageNameChanging(string value);
    partial void OnPackageNameChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnToLocationChanging(string value);
    partial void OnToLocationChanged();
    partial void OnVolumeChanging(double value);
    partial void OnVolumeChanged();
    partial void OnAccountPaybleChanging(System.Nullable<double> value);
    partial void OnAccountPaybleChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnDeductionsChanging(System.Nullable<double> value);
    partial void OnDeductionsChanged();
    partial void OnDeliverPriceChanging(System.Nullable<double> value);
    partial void OnDeliverPriceChanged();
    partial void OnDeliverTypeChanging(string value);
    partial void OnDeliverTypeChanged();
    partial void OnHandlingFeeChanging(System.Nullable<double> value);
    partial void OnHandlingFeeChanged();
    partial void OnPayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayDateChanged();
    partial void OnPrePayChanging(System.Nullable<double> value);
    partial void OnPrePayChanged();
    partial void OnOilCardChanging(System.Nullable<double> value);
    partial void OnOilCardChanged();
    partial void OnReparationsChanging(System.Nullable<double> value);
    partial void OnReparationsChanged();
    partial void OnShortBargeFeeChanging(System.Nullable<double> value);
    partial void OnShortBargeFeeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTrayNoChanging(string value);
    partial void OnTrayNoChanged();
    #endregion
		
		public TransportRecords()
		{
			this._TransportRecordsOptionHistory = new EntitySet<TransportRecordsOptionHistory>(new Action<TransportRecordsOptionHistory>(this.attach_TransportRecordsOptionHistory), new Action<TransportRecordsOptionHistory>(this.detach_TransportRecordsOptionHistory));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarLicense", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CarLicense
		{
			get
			{
				return this._CarLicense;
			}
			set
			{
				if ((this._CarLicense != value))
				{
					this.OnCarLicenseChanging(value);
					this.SendPropertyChanging();
					this._CarLicense = value;
					this.SendPropertyChanged("CarLicense");
					this.OnCarLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this.OnClientNameChanging(value);
					this.SendPropertyChanging();
					this._ClientName = value;
					this.SendPropertyChanged("ClientName");
					this.OnClientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliverDate", DbType="DateTime NOT NULL")]
		public System.DateTime DeliverDate
		{
			get
			{
				return this._DeliverDate;
			}
			set
			{
				if ((this._DeliverDate != value))
				{
					this.OnDeliverDateChanging(value);
					this.SendPropertyChanging();
					this._DeliverDate = value;
					this.SendPropertyChanged("DeliverDate");
					this.OnDeliverDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Driver", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Driver
		{
			get
			{
				return this._Driver;
			}
			set
			{
				if ((this._Driver != value))
				{
					this.OnDriverChanging(value);
					this.SendPropertyChanging();
					this._Driver = value;
					this.SendPropertyChanged("Driver");
					this.OnDriverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromLocation", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FromLocation
		{
			get
			{
				return this._FromLocation;
			}
			set
			{
				if ((this._FromLocation != value))
				{
					this.OnFromLocationChanging(value);
					this.SendPropertyChanging();
					this._FromLocation = value;
					this.SendPropertyChanged("FromLocation");
					this.OnFromLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this.OnPackageNameChanging(value);
					this.SendPropertyChanging();
					this._PackageName = value;
					this.SendPropertyChanged("PackageName");
					this.OnPackageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToLocation", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ToLocation
		{
			get
			{
				return this._ToLocation;
			}
			set
			{
				if ((this._ToLocation != value))
				{
					this.OnToLocationChanging(value);
					this.SendPropertyChanging();
					this._ToLocation = value;
					this.SendPropertyChanged("ToLocation");
					this.OnToLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float NOT NULL")]
		public double Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountPayble", DbType="Float")]
		public System.Nullable<double> AccountPayble
		{
			get
			{
				return this._AccountPayble;
			}
			set
			{
				if ((this._AccountPayble != value))
				{
					this.OnAccountPaybleChanging(value);
					this.SendPropertyChanging();
					this._AccountPayble = value;
					this.SendPropertyChanged("AccountPayble");
					this.OnAccountPaybleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deductions", DbType="Float")]
		public System.Nullable<double> Deductions
		{
			get
			{
				return this._Deductions;
			}
			set
			{
				if ((this._Deductions != value))
				{
					this.OnDeductionsChanging(value);
					this.SendPropertyChanging();
					this._Deductions = value;
					this.SendPropertyChanged("Deductions");
					this.OnDeductionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliverPrice", DbType="Float")]
		public System.Nullable<double> DeliverPrice
		{
			get
			{
				return this._DeliverPrice;
			}
			set
			{
				if ((this._DeliverPrice != value))
				{
					this.OnDeliverPriceChanging(value);
					this.SendPropertyChanging();
					this._DeliverPrice = value;
					this.SendPropertyChanged("DeliverPrice");
					this.OnDeliverPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliverType", DbType="NVarChar(255)")]
		public string DeliverType
		{
			get
			{
				return this._DeliverType;
			}
			set
			{
				if ((this._DeliverType != value))
				{
					this.OnDeliverTypeChanging(value);
					this.SendPropertyChanging();
					this._DeliverType = value;
					this.SendPropertyChanged("DeliverType");
					this.OnDeliverTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandlingFee", DbType="Float")]
		public System.Nullable<double> HandlingFee
		{
			get
			{
				return this._HandlingFee;
			}
			set
			{
				if ((this._HandlingFee != value))
				{
					this.OnHandlingFeeChanging(value);
					this.SendPropertyChanging();
					this._HandlingFee = value;
					this.SendPropertyChanged("HandlingFee");
					this.OnHandlingFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PayDate
		{
			get
			{
				return this._PayDate;
			}
			set
			{
				if ((this._PayDate != value))
				{
					this.OnPayDateChanging(value);
					this.SendPropertyChanging();
					this._PayDate = value;
					this.SendPropertyChanged("PayDate");
					this.OnPayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrePay", DbType="Float")]
		public System.Nullable<double> PrePay
		{
			get
			{
				return this._PrePay;
			}
			set
			{
				if ((this._PrePay != value))
				{
					this.OnPrePayChanging(value);
					this.SendPropertyChanging();
					this._PrePay = value;
					this.SendPropertyChanged("PrePay");
					this.OnPrePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilCard", DbType="Float")]
		public System.Nullable<double> OilCard
		{
			get
			{
				return this._OilCard;
			}
			set
			{
				if ((this._OilCard != value))
				{
					this.OnOilCardChanging(value);
					this.SendPropertyChanging();
					this._OilCard = value;
					this.SendPropertyChanged("OilCard");
					this.OnOilCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reparations", DbType="Float")]
		public System.Nullable<double> Reparations
		{
			get
			{
				return this._Reparations;
			}
			set
			{
				if ((this._Reparations != value))
				{
					this.OnReparationsChanging(value);
					this.SendPropertyChanging();
					this._Reparations = value;
					this.SendPropertyChanged("Reparations");
					this.OnReparationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortBargeFee", DbType="Float")]
		public System.Nullable<double> ShortBargeFee
		{
			get
			{
				return this._ShortBargeFee;
			}
			set
			{
				if ((this._ShortBargeFee != value))
				{
					this.OnShortBargeFeeChanging(value);
					this.SendPropertyChanging();
					this._ShortBargeFee = value;
					this.SendPropertyChanged("ShortBargeFee");
					this.OnShortBargeFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrayNo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TrayNo
		{
			get
			{
				return this._TrayNo;
			}
			set
			{
				if ((this._TrayNo != value))
				{
					this.OnTrayNoChanging(value);
					this.SendPropertyChanging();
					this._TrayNo = value;
					this.SendPropertyChanged("TrayNo");
					this.OnTrayNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransportRecords_TransportRecordsOptionHistory", Storage="_TransportRecordsOptionHistory", ThisKey="ID", OtherKey="TransportRecordID")]
		public EntitySet<TransportRecordsOptionHistory> TransportRecordsOptionHistory
		{
			get
			{
				return this._TransportRecordsOptionHistory;
			}
			set
			{
				this._TransportRecordsOptionHistory.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransportRecordsOptionHistory(TransportRecordsOptionHistory entity)
		{
			this.SendPropertyChanging();
			entity.TransportRecords = this;
		}
		
		private void detach_TransportRecordsOptionHistory(TransportRecordsOptionHistory entity)
		{
			this.SendPropertyChanging();
			entity.TransportRecords = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransportRecordsOptionHistory")]
	public partial class TransportRecordsOptionHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private int _TransportRecordID;
		
		private System.DateTime _LogDateTime;
		
		private string _Operation;
		
		private string _Description;
		
		private EntityRef<TransportRecords> _TransportRecords;
		
		private EntityRef<Users> _Users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnTransportRecordIDChanging(int value);
    partial void OnTransportRecordIDChanged();
    partial void OnLogDateTimeChanging(System.DateTime value);
    partial void OnLogDateTimeChanged();
    partial void OnOperationChanging(string value);
    partial void OnOperationChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TransportRecordsOptionHistory()
		{
			this._TransportRecords = default(EntityRef<TransportRecords>);
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportRecordID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TransportRecordID
		{
			get
			{
				return this._TransportRecordID;
			}
			set
			{
				if ((this._TransportRecordID != value))
				{
					if (this._TransportRecords.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransportRecordIDChanging(value);
					this.SendPropertyChanging();
					this._TransportRecordID = value;
					this.SendPropertyChanged("TransportRecordID");
					this.OnTransportRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDateTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime LogDateTime
		{
			get
			{
				return this._LogDateTime;
			}
			set
			{
				if ((this._LogDateTime != value))
				{
					this.OnLogDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LogDateTime = value;
					this.SendPropertyChanged("LogDateTime");
					this.OnLogDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this.OnOperationChanging(value);
					this.SendPropertyChanging();
					this._Operation = value;
					this.SendPropertyChanged("Operation");
					this.OnOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransportRecords_TransportRecordsOptionHistory", Storage="_TransportRecords", ThisKey="TransportRecordID", OtherKey="ID", IsForeignKey=true)]
		public TransportRecords TransportRecords
		{
			get
			{
				return this._TransportRecords.Entity;
			}
			set
			{
				TransportRecords previousValue = this._TransportRecords.Entity;
				if (((previousValue != value) 
							|| (this._TransportRecords.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TransportRecords.Entity = null;
						previousValue.TransportRecordsOptionHistory.Remove(this);
					}
					this._TransportRecords.Entity = value;
					if ((value != null))
					{
						value.TransportRecordsOptionHistory.Add(this);
						this._TransportRecordID = value.ID;
					}
					else
					{
						this._TransportRecordID = default(int);
					}
					this.SendPropertyChanged("TransportRecords");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_TransportRecordsOptionHistory", Storage="_Users", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.TransportRecordsOptionHistory.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.TransportRecordsOptionHistory.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuAccess")]
	public partial class MenuAccess : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MenuCode;
		
		private int _RoleID;
		
		private EntityRef<MenuItem> _MenuItem;
		
		private EntityRef<Roles> _Roles;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuCodeChanging(string value);
    partial void OnMenuCodeChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    #endregion
		
		public MenuAccess()
		{
			this._MenuItem = default(EntityRef<MenuItem>);
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MenuCode
		{
			get
			{
				return this._MenuCode;
			}
			set
			{
				if ((this._MenuCode != value))
				{
					if (this._MenuItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuCodeChanging(value);
					this.SendPropertyChanging();
					this._MenuCode = value;
					this.SendPropertyChanged("MenuCode");
					this.OnMenuCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_MenuAccess", Storage="_MenuItem", ThisKey="MenuCode", OtherKey="MenuCode", IsForeignKey=true)]
		public MenuItem MenuItem
		{
			get
			{
				return this._MenuItem.Entity;
			}
			set
			{
				MenuItem previousValue = this._MenuItem.Entity;
				if (((previousValue != value) 
							|| (this._MenuItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuItem.Entity = null;
						previousValue.MenuAccess.Remove(this);
					}
					this._MenuItem.Entity = value;
					if ((value != null))
					{
						value.MenuAccess.Add(this);
						this._MenuCode = value.MenuCode;
					}
					else
					{
						this._MenuCode = default(string);
					}
					this.SendPropertyChanged("MenuItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_MenuAccess", Storage="_Roles", ThisKey="RoleID", OtherKey="RoleID", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.MenuAccess.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.MenuAccess.Add(this);
						this._RoleID = value.RoleID;
					}
					else
					{
						this._RoleID = default(int);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuItem")]
	public partial class MenuItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MenuCode;
		
		private string _MenuText;
		
		private string _Link;
		
		private int _OrderIndex;
		
		private EntitySet<MenuAccess> _MenuAccess;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuCodeChanging(string value);
    partial void OnMenuCodeChanged();
    partial void OnMenuTextChanging(string value);
    partial void OnMenuTextChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnOrderIndexChanging(int value);
    partial void OnOrderIndexChanged();
    #endregion
		
		public MenuItem()
		{
			this._MenuAccess = new EntitySet<MenuAccess>(new Action<MenuAccess>(this.attach_MenuAccess), new Action<MenuAccess>(this.detach_MenuAccess));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MenuCode
		{
			get
			{
				return this._MenuCode;
			}
			set
			{
				if ((this._MenuCode != value))
				{
					this.OnMenuCodeChanging(value);
					this.SendPropertyChanging();
					this._MenuCode = value;
					this.SendPropertyChanged("MenuCode");
					this.OnMenuCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuText", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MenuText
		{
			get
			{
				return this._MenuText;
			}
			set
			{
				if ((this._MenuText != value))
				{
					this.OnMenuTextChanging(value);
					this.SendPropertyChanging();
					this._MenuText = value;
					this.SendPropertyChanged("MenuText");
					this.OnMenuTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderIndex", DbType="Int NOT NULL")]
		public int OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_MenuAccess", Storage="_MenuAccess", ThisKey="MenuCode", OtherKey="MenuCode")]
		public EntitySet<MenuAccess> MenuAccess
		{
			get
			{
				return this._MenuAccess;
			}
			set
			{
				this._MenuAccess.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuAccess(MenuAccess entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = this;
		}
		
		private void detach_MenuAccess(MenuAccess entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _Password;
		
		private System.DateTime _CreateDateTime;
		
		private int _RoleId;
		
		private string _Comment;
		
		private int _AreaID;
		
		private System.DateTime _LastLoginTime;
		
		private string _LastLoginIP;
		
		private string _Name;
		
		private EntitySet<TransportRecordsOptionHistory> _TransportRecordsOptionHistory;
		
		private EntityRef<BusinessArea> _BusinessArea;
		
		private EntityRef<Roles> _Roles;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCreateDateTimeChanging(System.DateTime value);
    partial void OnCreateDateTimeChanged();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnAreaIDChanging(int value);
    partial void OnAreaIDChanged();
    partial void OnLastLoginTimeChanging(System.DateTime value);
    partial void OnLastLoginTimeChanged();
    partial void OnLastLoginIPChanging(string value);
    partial void OnLastLoginIPChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Users()
		{
			this._TransportRecordsOptionHistory = new EntitySet<TransportRecordsOptionHistory>(new Action<TransportRecordsOptionHistory>(this.attach_TransportRecordsOptionHistory), new Action<TransportRecordsOptionHistory>(this.detach_TransportRecordsOptionHistory));
			this._BusinessArea = default(EntityRef<BusinessArea>);
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDateTime
		{
			get
			{
				return this._CreateDateTime;
			}
			set
			{
				if ((this._CreateDateTime != value))
				{
					this.OnCreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateDateTime = value;
					this.SendPropertyChanged("CreateDateTime");
					this.OnCreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int NOT NULL")]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaID", DbType="Int NOT NULL")]
		public int AreaID
		{
			get
			{
				return this._AreaID;
			}
			set
			{
				if ((this._AreaID != value))
				{
					if (this._BusinessArea.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAreaIDChanging(value);
					this.SendPropertyChanging();
					this._AreaID = value;
					this.SendPropertyChanged("AreaID");
					this.OnAreaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginTime", DbType="DateTime NOT NULL")]
		public System.DateTime LastLoginTime
		{
			get
			{
				return this._LastLoginTime;
			}
			set
			{
				if ((this._LastLoginTime != value))
				{
					this.OnLastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LastLoginTime = value;
					this.SendPropertyChanged("LastLoginTime");
					this.OnLastLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginIP", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LastLoginIP
		{
			get
			{
				return this._LastLoginIP;
			}
			set
			{
				if ((this._LastLoginIP != value))
				{
					this.OnLastLoginIPChanging(value);
					this.SendPropertyChanging();
					this._LastLoginIP = value;
					this.SendPropertyChanged("LastLoginIP");
					this.OnLastLoginIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_TransportRecordsOptionHistory", Storage="_TransportRecordsOptionHistory", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<TransportRecordsOptionHistory> TransportRecordsOptionHistory
		{
			get
			{
				return this._TransportRecordsOptionHistory;
			}
			set
			{
				this._TransportRecordsOptionHistory.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BusinessArea_Users", Storage="_BusinessArea", ThisKey="AreaID", OtherKey="ID", IsForeignKey=true)]
		public BusinessArea BusinessArea
		{
			get
			{
				return this._BusinessArea.Entity;
			}
			set
			{
				BusinessArea previousValue = this._BusinessArea.Entity;
				if (((previousValue != value) 
							|| (this._BusinessArea.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BusinessArea.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._BusinessArea.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._AreaID = value.ID;
					}
					else
					{
						this._AreaID = default(int);
					}
					this.SendPropertyChanged("BusinessArea");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Users", Storage="_Roles", ThisKey="RoleId", OtherKey="RoleID", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._RoleId = value.RoleID;
					}
					else
					{
						this._RoleId = default(int);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransportRecordsOptionHistory(TransportRecordsOptionHistory entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_TransportRecordsOptionHistory(TransportRecordsOptionHistory entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BusinessArea")]
	public partial class BusinessArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AreaName;
		
		private EntitySet<Users> _Users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAreaNameChanging(string value);
    partial void OnAreaNameChanged();
    #endregion
		
		public BusinessArea()
		{
			this._Users = new EntitySet<Users>(new Action<Users>(this.attach_Users), new Action<Users>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AreaName
		{
			get
			{
				return this._AreaName;
			}
			set
			{
				if ((this._AreaName != value))
				{
					this.OnAreaNameChanging(value);
					this.SendPropertyChanging();
					this._AreaName = value;
					this.SendPropertyChanged("AreaName");
					this.OnAreaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BusinessArea_Users", Storage="_Users", ThisKey="ID", OtherKey="AreaID")]
		public EntitySet<Users> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.BusinessArea = this;
		}
		
		private void detach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.BusinessArea = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _RoleName;
		
		private string _AccessList;
		
		private EntitySet<MenuAccess> _MenuAccess;
		
		private EntitySet<Users> _Users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnAccessListChanging(string value);
    partial void OnAccessListChanged();
    #endregion
		
		public Roles()
		{
			this._MenuAccess = new EntitySet<MenuAccess>(new Action<MenuAccess>(this.attach_MenuAccess), new Action<MenuAccess>(this.detach_MenuAccess));
			this._Users = new EntitySet<Users>(new Action<Users>(this.attach_Users), new Action<Users>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(255)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessList", DbType="NVarChar(500)")]
		public string AccessList
		{
			get
			{
				return this._AccessList;
			}
			set
			{
				if ((this._AccessList != value))
				{
					this.OnAccessListChanging(value);
					this.SendPropertyChanging();
					this._AccessList = value;
					this.SendPropertyChanged("AccessList");
					this.OnAccessListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_MenuAccess", Storage="_MenuAccess", ThisKey="RoleID", OtherKey="RoleID")]
		public EntitySet<MenuAccess> MenuAccess
		{
			get
			{
				return this._MenuAccess;
			}
			set
			{
				this._MenuAccess.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Users", Storage="_Users", ThisKey="RoleID", OtherKey="RoleId")]
		public EntitySet<Users> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuAccess(MenuAccess entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_MenuAccess(MenuAccess entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
		
		private void attach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
	}
}
#pragma warning restore 1591
